image: privacybydesign/node_yarn:latest

stages:
  - build

before_script:
  - set -euxo pipefail
  - apt-get update
  - apt-get install -y --no-install-recommends php composer
  - composer install
  - yarn install

build:
  stage: build
  script:
    - set -euxo pipefail
    - ./build.sh
    - mkdir build
    - cp -R ./{css,edugain,facebook,js,linkedin,surfnet,twitter,vendor} build
    - cp *.php build
    - rm build/*.sample.php
  artifacts:
    paths:
    - build/*
